Repository rhymix/rhymix, pull requests merged in 2018-08, with the labels that each got.

#1052 Add Soundcloud as a sharing service provider
  common/defaults/whitelist.php
Labels: question, someone else's problem

#1051 Improve cookie security; Secure flag
  classes/context/Context.class.php
  classes/mobile/Mobile.class.php
  common/framework/session.php
  common/js/common.js
  common/tpl/common_layout.html
  modules/admin/tpl/config_security.html
  modules/member/member.view.php
  widgets/login_info/skins/ncenter_login/js/ncenter.js
Labels: improvement

#1053 .btn 및 .message 클래스의 CSS 속성을 제거하는 옵션 제공 #950
  classes/display/HTMLDisplayHandler.php
  classes/frontendfile/FrontEndFileHandler.class.php
  common/css/mobile.css
  common/css/rhymix.less
  modules/admin/tpl/_header.html
  modules/admin/tpl/popup_layout.html
  modules/communication/m.skins/default/css/mcommunication.css
  modules/communication/skins/default/css/communication.css
  modules/member/skins/default/css/member.css
  tests/unit/classes/FrontEndFileHandlerTest.php
Labels: new feature

#1054 모듈 매니저 페이지에서 디자인이 깨지는 문제 수정
  classes/module/ModuleObject.class.php
  modules/admin/tpl/_footer.html
  modules/admin/tpl/_header.html
Labels: bug

#1058 스팸필터 모듈 개선
  modules/spamfilter/lang/en.php
  modules/spamfilter/lang/ja.php
  modules/spamfilter/lang/ko.php
  modules/spamfilter/schemas/spamfilter_denied_word.xml
  modules/spamfilter/spamfilter.admin.controller.php
  modules/spamfilter/spamfilter.model.php
  modules/spamfilter/tpl/css/spamfilter_admin.css
  modules/spamfilter/tpl/denied_word_list.html
  modules/spamfilter/tpl/header.html
Labels: new feature

#1067 쌍 따옴표가 있는 경우 메뉴 선택 문제 수정.
  modules/admin/tpl/js/admin.js
  modules/menu/tpl/sitemap.html
Labels: bug

#1072 숨겨진 관리자 설정의 설명을 보이도록 변경함
  modules/document/tpl/category_list.html
  modules/document/tpl/document_config.html
  modules/krzip/tpl/config.html
  modules/module/tpl/module_grant_setup.html
  modules/module/tpl/module_grants.html
  modules/module/tpl/module_setup.html
  modules/module/tpl/skin_config.html
  modules/ncenterlite/tpl/skinsetting.html
  modules/page/tpl/page_info.html
Labels: improvement

#1079 포인트 모듈의 기본 설정 화면 세세한 변경
  modules/point/tpl/config.html
Labels: improvement
