Repository rhymix/rhymix, pull requests merged in 2020-07, with the labels that each got.

#1336 SSL 선택적 사용 옵션 제거 #1323
  classes/context/Context.class.php
  common/framework/parsers/configparser.php
  common/framework/parsers/moduleactionparser.php
  common/tpl/common_layout.html
  modules/admin/lang/en.php
  modules/admin/lang/es.php
  modules/admin/lang/fr.php
  modules/admin/lang/ja.php
  modules/admin/lang/ko.php
  modules/admin/lang/ru.php
  modules/admin/lang/tr.php
  modules/admin/lang/vi.php
  modules/admin/lang/zh-CN.php
  modules/admin/lang/zh-TW.php
  modules/admin/tpl/config_domains_edit.html
  modules/board/conf/module.xml
  modules/document/conf/module.xml
  modules/install/install.admin.controller.php
  modules/install/tpl/other_config.html
  modules/member/conf/module.xml
  modules/module/module.controller.php
  modules/module/module.model.php
  modules/module/queries/deleteActionSecurity.xml
  modules/module/queries/getActionSecurity.xml
  modules/module/queries/insertActionSecurity.xml
  modules/module/schemas/action_security.xml
Labels: cleanup

#1347 #1244 최신 iOS 13.5.1에서 한글 입력시 엔터키 호환성 개선
  common/js/plugins/ckeditor/ckeditor/plugins/ios_enterkey/plugin.js
Labels: improvement

#1345 모바일에서 사용할 수 있는 간단한 위지윅 에디터 추가
  modules/editor/editor.admin.controller.php
  modules/editor/editor.admin.view.php
  modules/editor/editor.class.php
  modules/editor/editor.controller.php
  modules/editor/editor.model.php
  modules/editor/editor.view.php
  modules/editor/lang/en.php
  modules/editor/lang/ko.php
  modules/editor/skins/ckeditor/skin.xml
  modules/editor/skins/simpleeditor/css/simpleeditor.less
  modules/editor/skins/simpleeditor/editor.html
  modules/editor/skins/simpleeditor/js/interface.js
  modules/editor/skins/simpleeditor/js/simpleeditor.js
  modules/editor/skins/simpleeditor/skin.xml
  modules/editor/tpl/admin_index.html
  modules/editor/tpl/css/editor_module_config.css
  modules/editor/tpl/editor_module_config.html
  modules/editor/tpl/js/editor_module_config.js
Labels: new feature

#1354 CONTRIBUTING.md 일부 표현 수정
  CONTRIBUTING.md
Labels: improvement

#1357 회원 닉네임 변경 기록에 검색 옵션을 추가.
  modules/member/lang/ko.php
  modules/member/member.class.php
  modules/member/member.model.php
  modules/member/queries/getMemberModifyNickName.xml
  modules/member/schemas/member_nickname_log.xml
  modules/member/tpl/nick_name_log.html
Labels: improvement
