Repository rhymix/rhymix, pull requests merged in 2020-12, with the labels that each got.

#1475 확장변수에 국가번호를 포함한 전화번호, 언어, 시간, 국가 선택할 수 있는 확장변수를 추가
  classes/extravar/Extravar.class.php
  common/lang/de.php
  common/lang/en.php
  common/lang/es.php
  common/lang/fr.php
  common/lang/ja.php
  common/lang/ko.php
  common/lang/mn.php
  common/lang/ru.php
  common/lang/tr.php
  common/lang/vi.php
  common/lang/zh-CN.php
  common/lang/zh-TW.php
Labels: improvement

#1482 다크모드 감지 및 설정을 위한 rx_color_scheme 쿠키값의 표준화
  classes/context/Context.class.php
  common/framework/ua.php
  common/js/common.js
  tests/unit/framework/UATest.php
Labels: new feature

#1493 알림센터 유저 설정 세분화 (#994)
  modules/member/skins/default/css/member.css
  modules/ncenterlite/lang/en.php
  modules/ncenterlite/lang/ko.php
  modules/ncenterlite/ncenterlite.admin.view.php
  modules/ncenterlite/ncenterlite.class.php
  modules/ncenterlite/ncenterlite.controller.php
  modules/ncenterlite/ncenterlite.model.php
  modules/ncenterlite/ncenterlite.view.php
  modules/ncenterlite/queries/getNotifyType.xml
  modules/ncenterlite/queries/insertNotify.xml
  modules/ncenterlite/schemas/ncenterlite_user_set.xml
  modules/ncenterlite/skins/default/userconfig.html
  modules/ncenterlite/skins/default_bottom/userconfig.html
  modules/ncenterlite/tpl/config.html
  modules/ncenterlite/tpl/othercomment.html
Labels: improvement

#1494 코어에 포함된 애드온, 모듈, 위젯 등의 버전을 별도로 표기하지 않음
  addons/adminlogging/conf/info.xml
  addons/autolink/conf/info.xml
  addons/counter/conf/info.xml
  addons/member_extra_info/conf/info.xml
  addons/photoswipe/conf/info.xml
  addons/point_level_icon/conf/info.xml
  addons/resize_image/conf/info.xml
  common/framework/parsers/moduleinfoparser.php
  modules/addon/addon.admin.model.php
  modules/addon/conf/info.xml
  modules/addon/tpl/addon_info.html
  modules/addon/tpl/addon_list.html
  modules/addon/tpl/setup_addon.html
  modules/admin/conf/info.xml
  modules/admin/tpl/css/admin.css
  modules/adminlogging/conf/info.xml
  modules/advanced_mailer/conf/info.xml
  modules/autoinstall/conf/info.xml
  modules/board/conf/info.xml
  modules/comment/conf/info.xml
  modules/communication/conf/info.xml
  modules/counter/conf/info.xml
  modules/document/conf/info.xml
  modules/editor/conf/info.xml
  modules/file/conf/info.xml
  modules/importer/conf/info.xml
  modules/install/conf/info.xml
  modules/integration_search/conf/info.xml
  modules/krzip/conf/info.xml
  modules/layout/conf/info.xml
  modules/member/conf/info.xml
  modules/menu/conf/info.xml
  modules/message/conf/info.xml
  modules/module/conf/info.xml
  modules/module/tpl/module_list.html
  modules/ncenterlite/conf/info.xml
  modules/page/conf/info.xml
  modules/point/conf/info.xml
  modules/poll/conf/info.xml
  modules/rss/conf/info.xml
  modules/session/conf/info.xml
  modules/spamfilter/conf/info.xml
  modules/tag/conf/info.xml
  modules/trash/conf/info.xml
  modules/widget/conf/info.xml
  modules/widget/tpl/downloaded_widget_list.html
  modules/widget/widget.model.php
  widgets/content/conf/info.xml
  widgets/counter_status/conf/info.xml
  widgets/language_select/conf/info.xml
  widgets/login_info/conf/info.xml
  widgets/mcontent/conf/info.xml
  widgets/pollWidget/conf/info.xml
  widgetstyles/simple/skin.xml
Labels: cleanup

#1512 DB query의 operator 중 'search'에서 따옴표 및 AND, OR 사용
  common/framework/parsers/dbquery/variablebase.php
Labels: improvement

#1518 통합검색 모듈에서 검색어가 이중으로 escape 되는 문제 수정
  modules/file/file.admin.model.php
  modules/file/queries/getFileList.xml
  modules/file/queries/getFileListByTargetStatus.xml
  modules/integration_search/integration_search.view.php
Labels: improvement

#1520 공지사항 리스트에도 트리거를 추가
  modules/document/document.model.php
Labels: new feature

#1514 신고 내역을 세션에 기록하는 방식 개선
  modules/document/document.controller.php
  modules/document/document.item.php
Labels: improvement

#1534 Update zh-CN.php
  modules/board/lang/zh-CN.php
Labels: translation
