Repository rhymix/rhymix, pull requests merged in 2020-05, with the labels that each got.

#1292 모듈 클래스 인스턴스를 직접 생성할 수 있도록 개선
  classes/context/Context.class.php
  classes/display/DisplayHandler.class.php
  classes/module/ModuleHandler.class.php
  classes/module/ModuleObject.class.php
  classes/object/Object.class.php
  common/framework/helpers/confighelper.php
  common/framework/helpers/sessionhelper.php
  common/framework/password.php
  common/framework/session.php
  common/framework/url.php
  common/legacy.php
  modules/admin/admin.admin.view.php
  modules/autoinstall/autoinstall.class.php
  modules/board/board.class.php
  modules/member/member.class.php
  modules/menu/menu.admin.controller.php
  modules/session/session.class.php
Labels: new feature

#1300 Update a skin html for user config. page of the notification module
  modules/ncenterlite/skins/default_bottom/unsubscribe.html
  modules/ncenterlite/skins/default_bottom/unsubscribeList.html
  modules/ncenterlite/skins/default_bottom/userconfig.html
Labels: bug

#1301 알림 수신 거부 기능을 드롭다운 메뉴에 추가
  modules/ncenterlite/lang/en.php
  modules/ncenterlite/lang/ko.php
  modules/ncenterlite/ncenterlite.class.php
  modules/ncenterlite/ncenterlite.controller.php
  modules/ncenterlite/ncenterlite.view.php
  modules/ncenterlite/skins/default/unsubscribe.html
  modules/ncenterlite/skins/default/unsubscribeList.html
Labels: improvement
