Repository rhymix/rhymix, pull requests merged in 2020-06, with the labels that each got.

#1309 count() 함수를 사용하기 전에, 셀 수 있는 변수인지 확인
  classes/context/Context.class.php
  classes/db/DB.class.php
  classes/db/queryparts/Query.class.php
  common/functions.php
  layouts/simple_world/layout.html
  m.layouts/colorCode/layout.html
  m.layouts/default/layout.html
  m.layouts/simpleGray/layout.html
  modules/module/module.controller.php
  widgets/content/skins/simple_rectangle/content.html
Labels: cleanup

#1312 #1311 exec_json 에서 callback_error 의 반환값에 따라 alert 하지 않도록 수정
  common/js/xml_handler.js
Labels: improvement

#1317 Fix XEtown URL
  layouts/xedition/demo/welcome_main.html
  modules/install/tpl/footer.html
  modules/integration_search/integration_search.mobile.php
Labels: cleanup

#1308 에디터 스타일 삭제
  common/css/rhymix.less
  modules/editor/editor.admin.controller.php
  modules/editor/editor.admin.view.php
  modules/editor/editor.class.php
  modules/editor/editor.controller.php
  modules/editor/editor.model.php
  modules/editor/editor.view.php
  modules/editor/lang/en.php
  modules/editor/lang/ja.php
  modules/editor/lang/ko.php
  modules/editor/lang/tr.php
  modules/editor/lang/vi.php
  modules/editor/lang/zh-CN.php
  modules/editor/lang/zh-TW.php
  modules/editor/skins/ckeditor/css/default.css
  modules/editor/skins/ckeditor/css/default.less
  modules/editor/skins/ckeditor/editor.html
  modules/editor/styles/ckeditor_light/editor.css
  modules/editor/styles/ckeditor_light/editor.html
  modules/editor/styles/ckeditor_light/img/bg_qmark.gif
  modules/editor/styles/ckeditor_light/skin.xml
  modules/editor/styles/ckeditor_light/style.css
  modules/editor/styles/ckeditor_light/style.ini
  modules/editor/styles/default/editor.css
  modules/editor/styles/default/editor.html
  modules/editor/styles/default/img/bg_qmark.gif
  modules/editor/styles/default/skin.xml
  modules/editor/styles/default/style.css
  modules/editor/styles/default/style.ini
  modules/editor/tpl/admin_index.html
  modules/editor/tpl/editor_module_config.html
Labels: cleanup, discussion

#1316 SolAPI SMS 드라이버 추가
  common/framework/drivers/sms/solapi.php
  modules/ncenterlite/ncenterlite.class.php
  modules/ncenterlite/ncenterlite.controller.php
  tests/unit/framework/SMSTest.php
Labels: improvement

#1320 에디터 스킨 스타일 추가 수정 (미세 수정)
  modules/editor/skins/ckeditor/css/default.less
Labels: cleanup

#1322 라우터(Router) 기능 추가
  .htaccess
  classes/context/Context.class.php
  classes/display/HTMLDisplayHandler.php
  classes/module/ModuleHandler.class.php
  classes/module/ModuleObject.class.php
  common/defaults/config.php
  common/framework/parsers/moduleactionparser.php
  common/framework/parsers/moduleinfoparser.php
  common/framework/router.php
  common/lang/en.php
  common/lang/ko.php
  common/manual/server_config/rhymix-nginx-subdir.conf
  common/manual/server_config/rhymix-nginx.conf
  modules/admin/admin.admin.controller.php
  modules/admin/admin.admin.view.php
  modules/admin/lang/en.php
  modules/admin/lang/ko.php
  modules/admin/tpl/config_advanced.html
  modules/board/board.class.php
  modules/board/board.view.php
  modules/board/conf/module.xml
  modules/document/conf/module.xml
  modules/install/install.admin.controller.php
  modules/integration_search/conf/module.xml
  modules/integration_search/integration_search.class.php
  modules/member/conf/module.xml
  modules/member/member.class.php
  modules/module/module.class.php
  modules/module/module.controller.php
  modules/module/module.model.php
  modules/module/queries/deleteActionSecurity.xml
  modules/module/queries/getActionSecurity.xml
  modules/module/queries/insertActionForward.xml
  modules/module/queries/insertActionSecurity.xml
  modules/module/schemas/action_forward.xml
  modules/module/schemas/action_security.xml
  tests/unit/classes/ContextTest.php
  tests/unit/framework/RouterTest.php
Labels: new feature

#1325 모바일 푸시 기능 추가
  common/framework/drivers/push/apns.php
  common/framework/drivers/push/base.php
  common/framework/drivers/push/fcm.php
  common/framework/drivers/pushinterface.php
  common/framework/push.php
  common/lang/en.php
  common/lang/ko.php
  modules/admin/admin.admin.controller.php
  modules/admin/admin.admin.view.php
  modules/admin/tpl/config_notification.html
  modules/advanced_mailer/lang/en.php
  modules/advanced_mailer/lang/ko.php
  modules/member/conf/module.xml
  modules/member/member.controller.php
  modules/member/queries/deleteMemberDevice.xml
  modules/member/queries/getMemberDevice.xml
  modules/member/queries/getMemberDeviceTokensByMemberSrl.xml
  modules/member/queries/insertMemberDevice.xml
  modules/member/queries/updateMemberDevice.xml
  modules/member/schemas/member_devices.xml
  modules/ncenterlite/lang/ko.php
  modules/ncenterlite/ncenterlite.admin.view.php
  modules/ncenterlite/ncenterlite.controller.php
  modules/ncenterlite/tpl/config.html
Labels: new feature

#1331 #1330 댓글에 텍스트가 없는 상태에서 휴지통으로 이동시 문제 고침.
  modules/comment/lang/en.php
  modules/comment/lang/ko.php
  modules/trash/tpl/trash_list.html
Labels: cleanup
